---
--- Generated by EmmyLua(https://github.com/EmmyLua)
--- Created by Li Guoteng.
--- DateTime: 2022/10/24 23:14
---

-- 1.参数列表
--  优惠券id
local voucherId = ARGV[1]
--  用户id
local userId = ARGV[2]
--  订单id
local orderId = ARGV[3]

-- 2.数据key
--  库存key
local stockKey = 'seckill:stock:' .. voucherId
--  订单key
local orderKey = 'seckill:order:' .. voucherId

-- 3.脚本业务
--  3.1判断库存是否充足 get stockKey
if (tonumber(redis.call('get', stockKey)) <= 0) then
    -- 库存不足
    return 1
end
--  3.2判断用户是否下单 SISMEMBER orderKey userId
--  如果userId在orderId中，返回1
if (redis.call('sismember', orderKey, userId) == 1) then
    --  3.3存在，说明是重复下单，返回2
    return 2
end
--  3.4扣库存 incrby stockKey -1
redis.call('incrby', stockKey, -1)
--  3.5下单(保存用户) sadd orderKey userId
redis.call('sadd', orderKey, userId)
--  3.6发送消息到队列中，XADD stream.orders * k1 v1 k2 v2 ...
redis.call('xadd', 'stream.orders', '*', 'userId', userId, 'voucherId', voucherId, 'id', orderId)
return 0 --成功返回0,  1,2代表失败